packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  prisma: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    "nestjs-zod>@nestjs/common": "12"
    "nestjs-zod>@nestjs/swagger": "12"

engineStrict: true
